server {
    listen 80;
    server_name _;

    root /usr/share/nginx/html;
    index index.html;

    location /static/ {
        try_files $uri =404;
        expires 7d;
        add_header Cache-Control "public";
    }

    location / {
        try_files $uri $uri/ $uri.html /index.html;
    }
}